### ISSUE TITLE
Error libgit2.so.1.2: cannot open shared object file 

### ISSUE THREAD

**Issue by LaurentOngaro** [AchetaGames/Epic-Asset-Manager#138]
After an update of my system (manjaro Gnome 41.1) , EAM refuses to start with the following error
`
epic_asset_manager: error while loading shared libraries: libgit2.so.1.2: cannot open shared object file: No such file or directory
`
I've tried to reinstall from AUR: same issue

**Comment by aknarts** [comment]
Rebuild should help, fixed your other issue with the build, sorry about that, the library changed on me. Report if it is still an issue.

**Comment by LaurentOngaro** [comment]
Yes, problem fixed, but .... I've got another one. I open a new issue
