### ISSUE TITLE
Installing UE Plugin Panics

### ISSUE THREAD

**Issue by tdbgamer** [AchetaGames/Epic-Asset-Manager#141]
**Describe the bug**
When installing Apparatus ECS plugin on UE4, I get this immediately after the download starts:
```thread 'Download Pool' panicked at 'called `Result::unwrap()` on an `Err` value: Message { msg: "u128 is not supported", location: None }', src/ui/widgets/download_manager/mod.rs:536:64```

**To Reproduce**
1. Install Apparatus plugin

**Expected behavior**
Installs plugin properly

**Screenshots**

**Desktop (please complete the following information):**
`Linux 5.10.84-1-MANJARO #1 SMP PREEMPT Wed Dec 8 09:50:30 UTC 2021 x86_64 GNU/Linux`

**Additional context**
This is the output with full backtrace:
```bash
$ RUST_BACKTRACE=full /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=epic_asset_manager --file-forwarding io.github.achetagames.epic_asset_manager
thread 'Download Pool' panicked at 'called `Result::unwrap()` on an `Err` value: Message { msg: "u128 is not supported", location: None }', src/ui/widgets/download_manager/mod.rs:536:64
stack backtrace:
   0:     0x55e57feb517c - <unknown>
   1:     0x55e57fedd21c - <unknown>
   2:     0x55e57feadfd5 - <unknown>
   3:     0x55e57feb7160 - <unknown>
   4:     0x55e57feb6d17 - <unknown>
   5:     0x55e57feb7814 - <unknown>
   6:     0x55e57feb72f0 - <unknown>
   7:     0x55e57feb5644 - <unknown>
   8:     0x55e57feb7259 - <unknown>
   9:     0x55e57f5f8831 - <unknown>
  10:     0x55e57f5f8923 - <unknown>
  11:     0x55e57f6ad603 - <unknown>
  12:     0x55e57f968f31 - <unknown>
  13:     0x55e57f96acff - <unknown>
  14:     0x55e57febe7e3 - <unknown>
  15:     0x7f586424e3ba - <unknown>
  16:     0x7f5864027b03 - clone
  17:                0x0 - <unknown>
```

**Comment by aknarts** [comment]
Published a new release on flathub, you should get the update soon, this does not exactly fix the issue, but the json manifest is not crucial for anything right now so it can be skipped in case of an issue like this. Though it is strange it happens, I can get any plugin to download just fine. Sadly I do not have access to that particular asset as it is kind of costly, but this should be a general fix for the issue you reported.

**Comment by tdbgamer** [comment]
Thanks for making a release so quickly, but it seems to still panic, but in a different place now:
```bash
thread 'main' panicked at 'failed to upgrade `obj` (if you don't want to panic, use @default-return)', src/ui/widgets/download_manager/download_item.rs:241:13
stack backtrace:
   0:     0x564206b1a25c - <unknown>
   1:     0x564206b41e7c - <unknown>
   2:     0x564206b126c5 - <unknown>
   3:     0x564206b1c2a0 - <unknown>
   4:     0x564206b1be55 - <unknown>
   5:     0x564206b1c954 - <unknown>
   6:     0x56420626fe55 - <unknown>
   7:     0x56420626d746 - <unknown>
   8:     0x56420623b0c1 - <unknown>
   9:     0x564206363c9f - <unknown>
  10:     0x7f1e287443a8 - <unknown>
  11:     0x7f1e287436d1 - g_main_context_dispatch
  12:     0x7f1e28743bb8 - <unknown>
  13:     0x7f1e28743c83 - g_main_context_iteration
  14:     0x7f1e28976c45 - g_application_run
  15:     0x5642063515ee - <unknown>
  16:     0x5642063b6f02 - <unknown>
  17:     0x56420626f1c3 - <unknown>
  18:     0x5642062a7249 - <unknown>
  19:     0x564206b19f3b - <unknown>
  20:     0x5642063b7302 - <unknown>
  21:     0x7f1e2802eb90 - __libc_start_main
  22:     0x564206261e5e - <unknown>
  23:                0x0 - <unknown>
```

**Comment by aknarts** [comment]
There is something funny going on on your side. Can you download other assets/plugins? I can "fix" this one as well but it would not make much sense as it would stop showing any download progress if this is allowed to gracefully fail(though it should probably do so anyway as hard GUI crash is not desirable).
