### ISSUE TITLE
vs code not detected c++ UE5

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [AchetaGames/Epic-Asset-Manager#158]
**Describe the bug**
title says it all

**To Reproduce**
1. install the flatpak
2. create new UE5 project
3. Go to create new c++ class
4. it says vs code is not installed, even though I gave UE5 full access to my file system

**Comment by aknarts** [comment]
Hi, this is more issue with Unreal not detecting vscode in all places it should. All I can do from my side is add the ability to change the source code accessor to something your system does have, otherwise you can build your project for editor and open it normally using something like this:
```
<PATH TO UE4>/Engine/Build/BatchFiles/Linux/Build.sh Linux Development -Project=<PATH TO PROJECTS>/<ProjectName>/<ProjectName>.uproject -TargetType=Editor
```
After that the project should open as expected

**Comment by Etaash-mathamsetty** [comment]
> Hi, this is more issue with Unreal not detecting vscode in all places it should. All I can do from my side is add the ability to change the source code accessor to something your system does have, otherwise you can build your project for editor and open it normally using something like this:
> 
> ```
> <PATH TO UE4>/Engine/Build/BatchFiles/Linux/Build.sh Linux Development -Project=<PATH TO PROJECTS>/<ProjectName>/<ProjectName>.uproject -TargetType=Editor
> ```
> 
> After that the project should open as expected

I can compile just fine with vs code, its just unreal engine can't detect it and so its not creating the c++ files I need.

**Comment by aknarts** [comment]
Does it happen only when you launch through EAM? or even if you launch outside? I know there is a sandboxing issue with flatpak where it essentially launches the Engine inside the flatpak so it might have issues finding things. If it is the same outside EAM you can also generate the project files...

```
<PATH TO UE4>/GenerateProjectFiles.sh -Game <PATH TO PROJECTS>/<ProjectName>/<ProjectName>.uproject
```

**Comment by Etaash-mathamsetty** [comment]
> Does it happen only when you launch through EAM? or even if you launch outside? I know there is a sandboxing issue with flatpak where it essentially launches the Engine inside the flatpak so it might have issues finding things. If it is the same outside EAM you can also generate the project files...
> 
> ```
> <PATH TO UE4>/GenerateProjectFiles.sh -Game <PATH TO PROJECTS>/<ProjectName>/<ProjectName>.uproject
> ```

lol it crashes if i run it outside of EAM

**Comment by aknarts** [comment]
If you downloaded it through EAM it extracted it from the docker image and you do not need to have docker to run it. There might be an actual issue with the package as it was built. I will test it and see what is going on there.

**Comment by Etaash-mathamsetty** [comment]
seems like mangohud was causing the issue of it not launching without flatpak. (I have it globally enabled)
