### ISSUE TITLE
Github auth panic

### ISSUE THREAD

**Issue by NSQY** [AchetaGames/Epic-Asset-Manager#161]
**Describe the bug**
Authing with github results in silent error, unable to proceed.

**To Reproduce**
1. flatpak install flathub io.github.achetagames.epic_asset_manager
2. Auth with EGS
3. Attempt to add Engine
4. Click 'configure github token in Preferences'
5. Supply username and token

**Expected behavior**
Expected to be authed with github

**Desktop**
Linux 5.17.0-249-tkg-cfs-llvm
Arch linux
Flatpak 1.12.7
Nvidia 510.60.02

**Error**
```RUST_BACKTRACE=full flatpak run io.github.achetagames.epic_asset_manager```
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Reqwest(reqwest::Error { kind: Status(403), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("ghcr.io")), port: None, path: "/v2/epicgames/unreal-engine/tags/list", query: None, fragment: None } })', src/ui/widgets/logged_in/engines/engine_detail.rs:600:30
stack backtrace:
   0:     0x55a074a0113c - <unknown>
   1:     0x55a074a2bb8c - <unknown>
   2:     0x55a0749f82b3 - <unknown>
   3:     0x55a074a03b02 - <unknown>
   4:     0x55a074a036e5 - <unknown>
   5:     0x55a074a04153 - <unknown>
   6:     0x55a074a03e70 - <unknown>
   7:     0x55a074a015e4 - <unknown>
   8:     0x55a074a03ba9 - <unknown>
   9:     0x55a074027c51 - <unknown>
  10:     0x55a074027d43 - <unknown>
  11:     0x55a07417f238 - <unknown>
  12:     0x55a0741ec847 - <unknown>
  13:     0x55a074a0c2e3 - <unknown>
  14:     0x7ff9d5c853ba - <unknown>
  15:     0x7ff9d5a5eb03 - clone
  16:                0x0 - <unknown>
```

**Comment by NSQY** [comment]
The problem was that I had not accepted the invitation to EG github org.

**Comment by aknarts** [comment]
I will still handle the panic here, I can drop in a notice that the authentication failed.
