### ISSUE TITLE
Slow engine download, speed decrease and without no return maximum download speed

### ISSUE THREAD

**Issue by EtereosDawn** [AchetaGames/Epic-Asset-Manager#176]
I really have no idea why it's slow. I'm on fedora 35 the speed is still slow no matter if you only have the PC on the network. on the monitor the download is also slow.
![image](https://user-images.githubusercontent.com/34200212/165013410-9e6dc133-bc9f-4a89-85ab-b35d0c6a0818.png)
![image](https://user-images.githubusercontent.com/34200212/165013871-69ecd686-4291-4ce8-8289-68a823a1543b.png)

**Comment by EtereosDawn** [comment]
ok sorry but a VPN fixed that! I recommend putting this in the readme so that users who have download problems use vpn. almost give up using the application for not being able to download.
![image](https://user-images.githubusercontent.com/34200212/165024319-2cd02635-2e95-4105-84eb-b177296ffcca.png)

**Comment by aknarts** [comment]
Just a curious question, what country did your VPN go to? Also this is more Github Issue than the app issue.
