### ISSUE TITLE
Blank Library screen

### ISSUE THREAD

**Issue by bugporter-dev** [AchetaGames/Epic-Asset-Manager#199]
**Describe the bug**
After starting the app through flatpak, the Library screen is blank, with no content.

**To Reproduce**
1. $ flatpak run io.github.achetagames.epic_asset_manager
2. Click Library
3. The Library is blank
4. A banner appears at the bottom with the message: org.freedesktop.Secret.Service not available for use, secrets stored insecurely!

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Epic-Asset-Manager: 3.5.2

**Additional context**
I can log in successfully. Projects and Engines also appear correctly.
The debug log printed to the console is attached.

[debug.log](https://github.com/AchetaGames/Epic-Asset-Manager/files/9127293/debug.log)

**Comment by bugporter-dev** [comment]
The same problem happens after compiling from source, without flatpak. But, even setting the log level to Debug or Trace, nothing appears on the console. Is there any log file generated?

Though, the banner about freedesktop.Secret.Service doesn't appear and it doesn't ask for the login credentials on restart (running through flatpak, it asks for the credentials on each run)

**Comment by aknarts** [comment]
The question is.. do you own any assets? I just wiped my cache and everything is loading as it should, is there a progress bar at the bottom?

The logs should get generated, them not appearing is strange.

**Comment by bugporter-dev** [comment]
The assets, of course! I was just checking if you were paying attention.

Actually, I am new to Unreal. I confused Library with Marketplace, and thought I needed the Asset Manager to get packages. but I just used the web marketplace. Maybe you can put some text saying the web marketplace is needed to get assets.

It is working fine now. This issue can be closed. Thanks for the app.
