### ISSUE TITLE
EULA fails to validate

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [AchetaGames/Epic-Asset-Manager#205]
**Describe the bug**

I was hoping to try the engine download, yet I keep being faced with `EULA Accepted? Please sign the EULA to continue`. However, I have already accepted the EULA. After digging around I found out that the EULA fails to load immediately when I open the app.

I'm using Flatpak on Pop_OS! 22.04.

**To Reproduce**
1. Open the App using the terminal (`flatpak run io.github.achetagames.epic_asset_manager`), after configuration.
2. Look at terminal messages
3. Notice `<epic_asset_manager::tools::epic_web> - [ERROR] - Failed to parse EULA json: error decoding response body: invalid type: null, expected struct HasAccountAccepted at line 1 column 743`
4. Go to Engines > Install Engine.
5. See `EULA Accepted? Please sign the EULA to continue` message.

_OR_

1. Open the App using the terminal (`flatpak run io.github.achetagames.epic_asset_manager`), after configuration.
2. Go to Engines > Install Engine.
3. See `EULA Accepted? Please sign the EULA to continue` message.
4. Click `Revalidate`
5. "Nothing" happens
6. Look at terminal messages
7. Notice `<epic_asset_manager::tools::epic_web> - [ERROR] - Failed to parse EULA json: error decoding response body: invalid type: null, expected struct HasAccountAccepted at line 1 column 743`

**Expected behavior**

1. Open the App after configuration.
2. Go to Engines > Install Engine.
3. See `EULA Accepted` message.
4. Install UE5

**Screenshots**

![image](https://user-images.githubusercontent.com/7673578/181536366-69a92d70-639d-47d8-af4b-fe2784869bdf.png)

**Desktop (please complete the following information):**
 - OS: Pop_OS! 22.04
 - Browser: Firefox 103

**Additional context**

I believe the issue is that the graph call is returning null instead of returning the expected values. My guess is that there were changes in the graph callback API or because my account is "old" it makes use of outdated calls.

The terminal logs are the following:

```
$ flatpak run io.github.achetagames.epic_asset_manager 
<epic_asset_manager> - [DEBUG] - /app/share/epic_asset_manager
<epic_asset_manager> - [DEBUG] - 
<epic_asset_manager> - [DEBUG] - 3.6.1
<epic_asset_manager::application> - [INFO] - Epic Asset Manager (io.github.achetagames.epic_asset_manager)
<epic_asset_manager::application> - [INFO] - Version: 3.6.1 ()
<epic_asset_manager::application> - [INFO] - Datadir: /app/share/epic_asset_manager
<epic_asset_manager::application::imp> - [DEBUG] - GtkApplication<EpicAssetManager>::startup
<epic_asset_manager::tools::epic_web> - [ERROR] - Failed to parse EULA json: error decoding response body: invalid type: null, expected struct HasAccountAccepted at line 1 column 743
```

The code seems to end up here:

https://github.com/AchetaGames/Epic-Asset-Manager/blob/470217d80c799d3e5da19b1d4e63a9867c18783b/src/tools/epic_web.rs#L144

**Comment by aknarts** [comment]
The feature is highly experimental, what happens in your case is that you are getting an unexpected result from the Epic API.
Can you please test the following?
 - In the Library bottom left, click the marketplace button, does it open OK and are you authenticated?
The actual request to authenticate EULA is not a simple one to reproduce(as it requires cookies to be set and particular data to be sent.
I will try adding a bit more output to the failed parsing just so we can see what you actually got.

In the mean time you can download the zip manually from here: https://www.unrealengine.com/en-US/linux it goes through the same EULA validation so it would be curious if you got different results there.

I would like to keep you for testing though as catching the edge cases is important.

**Comment by aknarts** [comment]
If you could install the flatpak from here(download at the bottom of the page) https://github.com/AchetaGames/Epic-Asset-Manager/actions/runs/2755938964 it should provide more output.

**Comment by geowarin** [comment]
Hi! I'm having the same problem. I'd like to help but I could not figure how to install the flatpak you pointed at.
Do I need to add another new remote?

**Comment by aknarts** [comment]
> Hi! I'm having the same problem. I'd like to help but I could not figure how to install the flatpak you pointed at. Do I need to add another new remote?

No you just do `flatpak install <file>` on the file contained within the zip that you can download on the link (I can release the extended output as a patch but did not get to it yet)

**Comment by geowarin** [comment]
Doh! Did not unzip it. .🤦‍♂️
Anyway, here is the log... Which is the exact same output as @RicardoEPRodrigues 

```
❯ flatpak run io.github.achetagames.epic_asset_manager.Devel 
<epic_asset_manager> - [DEBUG] - /app/share/epic_asset_manager
<epic_asset_manager> - [DEBUG] - Devel
<epic_asset_manager> - [DEBUG] - 3.6.1-c8c8194
<epic_asset_manager::application> - [INFO] - Epic Asset Manager (io.github.achetagames.epic_asset_manager.Devel)
<epic_asset_manager::application> - [INFO] - Version: 3.6.1-c8c8194 (Devel)
<epic_asset_manager::application> - [INFO] - Datadir: /app/share/epic_asset_manager
<epic_asset_manager::application::imp> - [DEBUG] - GtkApplication<EpicAssetManager>::startup
<epic_asset_manager::tools::epic_web> - [ERROR] - Failed to parse EULA json: invalid type: null, expected struct HasAccountAccepted at line 1 column 743
```

**Comment by aknarts** [comment]
That is what I get for disabling debug output on final build(I know it says DEBUG right above, but that is before the configuration is read:D). Can you please enable Debug output in settings and try again? (There is a button that rechecks EULA on the download page)

**Comment by geowarin** [comment]
```
<epic_asset_manager::tools::epic_web> - [ERROR] - Failed to parse EULA json: invalid type: null, expected struct HasAccountAccepted at line 1 column 743
<epic_asset_manager::tools::epic_web> - [DEBUG] - Response: {"errors":[{"message":"EulaQuery/hasAccountAccepted: Request failed with status code 403","locations":[{"line":1,"column":20}],"correlationId":"","serviceResponse":"{\"errorCode\":\"errors.com.epicgames.common.missing_permission\",\"errorMessage\":\"Sorry your login does not posses the permissions 'eulatracking:public:displayagreement:8645b4947bbc4c0092a8b7236df169d1 READ' needed to perform the requested operation\",\"messageVars\":[\"eulatracking:public:displayagreement:8645b4947bbc4c0092a8b7236df169d1\",\"READ\"],\"numericErrorCode\":1023,\"originatingService\":\"com.epicgames.eulatracking.public\",\"intent\":\"prod\",\"errorStatus\":403}","stack":null,"path":["Eula","hasAccountAccepted"]}],"data":{"Eula":{"hasAccountAccepted":null}},"extensions":{}}
```

Seems like I get a 403 error because of a missing permission

**Comment by aknarts** [comment]
Oh that is interesting, I will take a look into other ways of verifying the EULA is signed... Honestly it is not a technical requirement for me to check but a legal one so I might bypass it for now just to have this working and try to figure out the best way to query this.

**Comment by geowarin** [comment]
Maybe it's just missing when you request the token when you first login

**Comment by geowarin** [comment]
Ok so yeah, you're not requesting any permissions on the token generation:
https://www.epicgames.com/id/login?redirectUrl=https%3A%2F%2Fwww.epicgames.com%2Fid%2Fapi%2Fredirect

I suppose the protocol isn't documented anywhere...

**Comment by aknarts** [comment]
No, the process is the same for everybody and on my side the query works just fine. 

Would you be able to go to https://www.unrealengine.com/en-US/linux with Developer tools Network tab it performs two queries to graphql, one of those is the EULA query, does that succeed for you? 

And no this is not documented anywhere, kind of reverse engineering this from how their web does it.

**Comment by aknarts** [comment]
Plus if you can post the data sent and data received...

**Comment by aknarts** [comment]
Ok this is on me :D.. will have a fix in a minute...

**Comment by geowarin** [comment]
:smile: 

I've got the queries and the response if you still need them, but it seems you figured it out!

**Comment by aknarts** [comment]
Well it just hit me that 8645b4947bbc4c0092a8b7236df169d1 is not your account ID but mine ... would explain why it works for me... :D

**Comment by aknarts** [comment]
Would anyone be able to validate the fix?

**Comment by aknarts** [comment]
Pushing through flathub, or it is available here. If you installed from github actions before you might need to reinstall from flathub. (it is a different app ID so you probably have both at the same time)

**Comment by aknarts** [comment]
Feel free to comment here once the update reaches you... would like a confirmation this works.

**Comment by geowarin** [comment]
Confirmed working in 3.6.2. Thank you for your work @aknarts !

**Comment by aknarts** [comment]
Thanks for the feedback @geowarin . Considering this was my fault do not even mention it:).
That being said that particular post request that I messed up has been haunting me since I first saw it so I might look into it again in the future.

**Comment by RicardoEPRodrigues** [comment]
Sorry for my absence. I tried the new build and can confirm that it is working! Great work!

**Comment by ridiche34** [comment]
I have version 3.8.4 from FlatHub, but I have a similar issue. (says EULA not accepted, despite having accepted the EULA)
How do I view the log?
