### ISSUE TITLE
Epic-Asset-Manager crashes and closes the window after clicking and adding multiple assets to a download queue

### ISSUE THREAD

**Issue by firebitsbr** [AchetaGames/Epic-Asset-Manager#223]
**Describe the bug**
Epic-Asset-Manager crashes and closes the window after clicking and adding multiple assets to a download queue

**To Reproduce**
Epic-Asset-Manager crashes and closes the window after clicking and adding multiple assets to a download queue

**Expected behavior**
The ideal is to download multiple assets in a queue, without closing or crashing Epic-Asset-Manager.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - Browser Google chrome Version 107.0.5304.110 (Official Build) (64-bit)

**Additional context**
If the Epic-Asset-Manager crashes or closes, ideally, the download queue returns with the same download queue and status that it was in before the crash, so that we can continue the downloads.

**Comment by aknarts** [comment]
This might sound stupid but it works on my end, how do you have EAM installed? I will give you a command to run it with debug logs

**Comment by firebitsbr** [comment]
Step 1. Open a terminal;

Step 2. Use the command below to install the program via Flatpak:

$ flatpak install --user https://flathub.org/repo/appstream/io.github.achetagames.epic_asset_manager.flatpakref

Step 3. To update the program, when a new version is available, run the command:

$ flatpak --user update io.github.achetagames.epic_asset_manager

Ready! Now, when you want to start the program, type?

$ flatpak run io.github.achetagames.epic_asset_manager in a terminal.


Likely to be some problem between flatpak and the EPIC Games Manager?

I can try to compile it via source code or use some other repo or package if needed. What would the suggestion be? Thanks for replying to the topic.

**Comment by aknarts** [comment]
Flatpak is actually the preferred way to install and run EAM so you are fine..

Try with this and send me the crash log
```
flatpak run --env=RUST_LOG=debug io.github.achetagames.epic_asset_manager
```
This will spit out a whole lot of output to the terminal(you might also need to change the settings in EAM configuration to go for Debug).

**Comment by firebitsbr** [comment]
flatpak run --env=RUST_LOG=debug io.github.achetagames.epic_asset_manager
<epic_asset_manager> - [DEBUG] - /app/share/epic_asset_manager
<epic_asset_manager> - [DEBUG] - 
<epic_asset_manager> - [DEBUG] - 3.8.2
<epic_asset_manager::application> - [INFO] - Epic Asset Manager (io.github.achetagames.epic_asset_manager)
<epic_asset_manager::application> - [INFO] - Version: 3.8.2 ()
<epic_asset_manager::application> - [INFO] - Datadir: /app/share/epic_asset_manager
<epic_asset_manager::application::imp> - [DEBUG] - GtkApplication<EpicAssetManager>::startup
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("trailing comma", line: 6, column: 1)', src/models/project_data.rs:210:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by aknarts** [comment]
That is fun, means there is a formatting error in one of your .uproject files, will see if I can reproduce it and make the parsing more tolerant. Thanks for the log.

**Comment by nathaniel-zick** [comment]
I'm getting a basically the same error, but it's when I start EAM.

**Comment by aknarts** [comment]
> I'm getting a basically the same error, but it's when I start EAM. Right after opening it closes, and spits out this: <epic_asset_manager> - [DEBUG] - /app/share/epic_asset_manager <epic_asset_manager> - [DEBUG] - <epic_asset_manager> - [DEBUG] - 3.8.2 <epic_asset_manager::application> - [INFO] - Epic Asset Manager (io.github.achetagames.epic_asset_manager) <epic_asset_manager::application> - [INFO] - Version: 3.8.2 () <epic_asset_manager::application> - [INFO] - Datadir: /app/share/epic_asset_manager <epic_asset_manager::application::imp> - [DEBUG] - GtkApplication::startup thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: string "", expected a sequence", line: 6, column: 14)', src/models/project_data.rs:210:56 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

That is a widely different error that I can easily handle. Will take a look at it as soon as possible anyway, you might want to open another bug for it though.

**Comment by aknarts** [comment]
While this is marked as fixed and closed I would still like to get your guys .uproject file that is faling this. Added an extra log line that should capture it.
