### ISSUE TITLE
Library is empty despite owning assets

### ISSUE THREAD

**Issue by TheSunCat** [AchetaGames/Epic-Asset-Manager#247]
**Describe the bug**
The library shows an empty screen after logging in. An empty progress bar is shown at the bottom that says 0%, and to its right it says 0 items. My "vault" in the Unreal Engine marketplace shows I own assets, yet they don't show up in this app.

**To Reproduce**
1. Log in
2. Observe no assets

**Expected behavior**
Assets should be listed and downloadable

**Screenshots**
![image](https://github.com/AchetaGames/Epic-Asset-Manager/assets/44881120/b7834474-c218-42c2-ae22-f88239b7467b)

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Browser: Firefox
 - Version: AUR package `eam-git-3.8.4.r8.ga8cc879-1`

**Additional context**
Despite setting logging to Trace, nothing relevant is printed to the console:
```
(epic_asset_manager:35994): Gtk-WARNING **: 11:50:52.623: Theme parser error: gtk-dark.css:7791:21-28: Expected a valid color.

(epic_asset_manager:35994): Gtk-WARNING **: 11:50:52.623: Theme parser error: gtk-dark.css:7796:21-28: Expected a valid color.

(epic_asset_manager:35994): Gtk-WARNING **: 11:50:52.623: Theme parser error: gtk-dark.css:7814:21-28: Expected a valid color.

(epic_asset_manager:35994): Gtk-WARNING **: 11:50:52.623: Theme parser error: gtk-dark.css:7820:21-28: Expected a valid color.

(epic_asset_manager:35994): Adwaita-WARNING **: 11:50:52.636: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(epic_asset_manager:35994): Gtk-WARNING **: 11:50:52.851: AdwViewSwitcher 0x56207186f690 (viewswitcher) reported min height -6, but sizes must be >= 0
```

I also tried the Flatpak build, with no success.

**Comment by TheSunCat** [comment]
Oops, it was logging me into a different account than the marketplace one, with the same name (?). They show up now! Closing.

**Comment by aknarts** [comment]
You scared me there :). It also does take a bit for the assets to show up. Glad it works now.

**Comment by TheSunCat** [comment]
Yeah my bad!
Thanks for maintaining this, I have no idea how I'd survive this year of university on Linux without the Epic Asset Manager. Was considering getting a VM just to download assets and copy them in.
