### ISSUE TITLE
EGS crash with some assets

### ISSUE THREAD

**Issue by remi75** [AchetaGames/Epic-Asset-Manager#250]
**Describe the bug**
asset fails to be downloaded .

**To Reproduce**

Try to install MassiveWorld , GUI stops at initializing , for ever.

**Expected behavior**

MassiveWorld should download and install in a project.

**Screenshots**
thread 'Download Pool' panicked at /home/user/.cache/yay/eam-git/src/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/egs-api-0.6.0/src/api/utils.rs:43:30:
range end index 107218 out of range for slice of length 107215

**Desktop (please complete the following information):**
 an Arch linux based distro.
I have the same problem with the AUR version and the flatpak version.

**Additional context**
EAM has no problems with other assets . aur and flatpak .

I was able to download the asset with the  official Epic launcher.

This asset a not a free asset, I have bought it , having not tested all other assets I cant tell if it is the only difference with the other assets .

Thank you again for EAM  :)

**Comment by remi75** [comment]
### update: 

seems not related to free/non-free ... ?!

I have just bought 

https://www.unrealengine.com/marketplace/en-US/product/landscape-combinator

and it works .

but

https://www.unrealengine.com/marketplace/en-US/product/massive-world-procedural-generation-with-pcg

still doesn't work .

ps: the bug  #252  is the same as what i am talking about :)

**Comment by remi75** [comment]
![sefsdf](https://github.com/AchetaGames/Epic-Asset-Manager/assets/129165743/d42c19b9-17a3-4087-921e-36ba605f8bb3)

I noticed a difference between the incriminated assets and the "good" ones: the size field doesn't get populated,
it stays like this and never writes the Size .
with other assets it does display the sizes , whether already downloaded or not .

**Comment by aknarts** [comment]
I think the issue is "new" vs "old". The reason I requested a free one is that I have one that I can test on without needing to spend some excessive amount of money on an asset I do not need:).

**Comment by remi75** [comment]
You mean the age of the Asset ?

**Comment by aknarts** [comment]
I mean the time of the latest update. The Epic API is kind of a strange thing, it feels like there is some form of Mongo storage behind it and each asset has a unique format. The clearest example is that "Games" are in binary format and Unreal Assets are in json format. What is happening here is that some unknown field has changed from mandatory to optional, or something got removed/renamed.

**Comment by remi75** [comment]
possible "epic" has a bug but made some workaround in Their client (M$)... but "us" can see it ...

**Comment by aknarts** [comment]
Well no, this is a possible side effect of using Rust for the API, it is stricter on the fields that it gets. The initial setup of the API was done by essentially downloading all the assets I own and building a common structure that matches all of them. 

I am working on getting the app to the current GTK, it is/was a blocker for most of my work on it, this comes right after and should not take much longer.

**Comment by remi75** [comment]
Loaded the git version with Arch's AUR .

problem fixed thank you .
