### ISSUE TITLE
Assets won't download

### ISSUE THREAD

**Issue by remi75** [AchetaGames/Epic-Asset-Manager#254]
Asset doesn't start downloading

Try the "Medieval game Environment"

you get "failed downloading asset manifest"
and another symptom: doesn't display the size of the asset (technically normal?)

It happened with other assets, a quick fix by a restart, but it happened again,
so I tried a systematic restart after a download of an asset, but that didn't last .

I had a couple of versions ran before on this PC/user, if a reset of some cache is needed, I can try .
if a wipe-out of the assets is needed, I can try that too .

regards

**Comment by remi75** [comment]
I have done more tests with a fresh Linux account on the PC:
the application seems completely broken.
no asset get pulled.
pointing directories of the Unreal engine doesn't get saved or taken into consideration , could a reason for not getting the assets ... , created a fresh Unreal project, same problem: doesn't see it or takes it into consideration .

**Comment by aknarts** [comment]
What version are you on? I did merge in a fix for the manifest. So try updating that from flathub or whatever your installation source is

**Comment by aknarts** [comment]
Ah I see you use AUR.. I still need to update that package.

**Comment by remi75** [comment]
yes AUR, and I tested the flatpack version too, both are at 3.8.5 .
many packages do not get their size displayed , and those cant be installed for failure to get the manifest file/data .

**Comment by aknarts** [comment]
I have noticed the size missing as well, but the download did go through after that. I still need to see why the size is missing though.

**Comment by remi75** [comment]
I am attaching a log file, I took a non downloaded asset, that has the symptom described: not showing size and displaying "failure to get manifest ..." 
[eam.log.txt](https://github.com/AchetaGames/Epic-Asset-Manager/files/15293035/eam.log.txt)

regards

**Comment by zerocool128** [comment]
on 3.8.5 and does this to me as well. heeeeeeeelp...

**Comment by aknarts** [comment]
New version pushed yesterday, try it again.

**Comment by zerocool128** [comment]
I was trying again yesterday and does the same thing.

**Comment by remi75** [comment]
I updated the flatpak version : working great .
the AUR version too, both same latest version, both work.

If it matters to know: 

when you start downloading an asset A , then browse to an asset B ,
the size of the asset B doesn't get displayed (scared me in the beginning) 
as soon as the asset A finishes downloading , asset's B size get displayed and its download can start .
otherwise the stays on "initializing"
not a big problem , but we cant download assets in parallel, before I think we could .


Best regards and thank you again .

**Comment by aknarts** [comment]
The size display issue is similar in reason to what happens when the app crashes when you "quickly" switch to a different asset in the view.

**Comment by zerocool128** [comment]
Works great now...
