### ISSUE TITLE
[Question] How to connect to Epic's API?

### ISSUE THREAD

**Issue by Catley94** [AchetaGames/Epic-Asset-Manager#302]
Hey, 

So whilst reading through some of the issues and proposed changes, I saw that really this project is too fill a void that Epic caused by not having a client to add assets to others etc. 

I'm so very grateful for this project, thank you so much! 

But I am curious, since my Rust, is very rusty... ;) I was hoping if you could provide a short summary on how you're connecting to the Epic API so I can get further understanding. 

I'm curious on how to connect to Epic's API so I can get the assets stored on my account etc, like how you do it.

Obviously I will continue to look through the code and learn, but was hoping to have some help by someone explaining it. :) 

P.S I will also continue developing this project where I can whilst it's active. :)

**Comment by aknarts** [comment]
Check out https://github.com/AchetaGames/egs-api-rs it also now has the FAB capabilities.

**Comment by Catley94** [comment]
Thank you, I will take a look so I can understand it more. I very much like getting the whole picture approach so I can help in more than one way :-)
