### ISSUE TITLE
Stuck on "Resuming session" -- clear local data to force login?

### ISSUE THREAD

**Issue by samuelgundry** [AchetaGames/Epic-Asset-Manager#63]
Installed from source (9081193c44d0), and I'm stuck on "Resuming session" splash screen on every start. It worked once but not sure what triggered this issued. 

I am unfamiliar with meso/cargo/gtk applications -- is there a local user preferences/data I can remove to force a new login?  I've tried re-installing. 

The terminal stdout shows:

```
Starting relogin
Changed the message
Shown process
```

**Comment by aknarts** [comment]
Hi, sorry about that it is one of the known issues. 

remove the `~/.config/epic_asset_manager/user.json` file and that will force the relogin. 

I do have a fix for this in the gtk4 branch but that branch is not ready to be used yet(does not download yet) and does not update things from the API yet, but is nearing completion.

**Comment by samuelgundry** [comment]
Fixed, thank you!
