### ISSUE TITLE
Requirements in the readme

### ISSUE THREAD

**Issue by edap** [AchetaGames/Epic-Asset-Manager#69]
Hello, I am trying to install this software but I am not sure about the dependencies.
I am on pop os, in the readme it is written that gtk3 is required but in the meson.build file is written `dependency('gtk4', version: '>= 4.0.0')`.

**Comment by aknarts** [comment]
Sorry about that, did not check that part when I did the gtk4 rewrite. To be fair I have been very focused on making it to [flathub.org](https://flathub.org/apps/details/io.github.achetagames.epic_asset_manager) which does take care of the dependencies. Will fix the manual build steps shortly.
