### ISSUE TITLE
Asset download freezes sometimes

### ISSUE THREAD

**Issue by LaurentOngaro** [AchetaGames/Epic-Asset-Manager#73]
Sometime, downloading an asset just freeze. 
Download starts but after a while it stop and nothing moves after that.

If I launch the tools in a terminal, in that case, I can see the following error:

`
Allocating size to AdwGizmo 0x5572d5b09f60 without calling gtk_widget_measure(). How does the code know the size to allocate?
thread 'Download Pool' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("fastly-download.epicgames.com")), port: None, path: "/Builds/Rocket/Automated/EnginePlugins/FirstPersonCharacter/CloudDir/ChunksV3/59/C4101E0AC6A10B91_08D4E8864EBB463D989BB38584EB1A6A.chunk", query: None, fragment: None }, source: TimedOut }', src/ui/widgets/download_manager/mod.rs:594:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

It seems to occur randomly.

Relaunching the same download does nothing.

If I close the program, the windows disappears but there is still an "epic_asset_manager" process that runs in background and take some CPU time (6% on my Ryzen 3700x CPU). 
I can't relaunch the program in that state
I must kill the process 
Once done, I can relaunch the tool.

Perhaps, having a button to stop or restart a download could be a good work around

My system is Manjaro Gnome up to date

**Comment by aknarts** [comment]
There are two issues there, the one that it panics on I can fix quite easily and will do so soon(thanks for the trace). 

The second is the application not closing when you close it. I know about this and am looking into how best solve this. What is happening there is there is a lot of work queued up in the thread pool and it needs to finish processing it before that work is finished. I am looking into options how to signal those threads to die before their time and will double that effort. As a side note which asset is this failing on?

**Comment by LaurentOngaro** [comment]
OK, thanks for that too !

**Comment by aknarts** [comment]
This should be partially fixed in https://github.com/AchetaGames/Epic-Asset-Manager/releases/tag/v2.3.0. I am not exceptionally happy with the fix as I am essentially just retrying the same download which does have the risk of the download just infinitely looping. I will close this in favor of #76.
