### ISSUE TITLE
feature request: Dark mode/theme

### ISSUE THREAD

**Issue by Ryder17z** [AchetaGames/Epic-Asset-Manager#90]
**Is your feature request related to a problem? Please describe.**
This white theme looks very much out-of-place when the system theme is dark.

**Describe the solution you'd like**
Dark mode/theme

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by aknarts** [comment]
Hi, this is something that is an upstream issue with libadwaita and should be solved in the next release of the library, yes, my eyes hurt as well. I am currently exploring a way to work around their issue so possibly stay tuned.
