### ISSUE TITLE
Login process stuck on "Authenticating"

### ISSUE THREAD

**Issue by iSaluki** [AchetaGames/Epic-Asset-Manager#96]
**Describe the bug**
The program gets stuck on the "Authenticating" screen after entering your sid on Manjaro KDE.

**To Reproduce**
1. Open pamac
2. Search for Epic Asset Manager
3. Download the flatpak
4. Open and enter SID
5. Observe perpetual loading issue

**Expected behavior**
The login should complete and the application should run as normal.

**Screenshots**
![Screenshot_20211101_153654](https://user-images.githubusercontent.com/37915796/139698431-40f678d4-4eb1-4037-9214-b907a1e8e9f3.png)

**Desktop (please complete the following information):**
 - OS: Manjaro x86 Stable (KDE Plasma 5.22.5)
 - Browser: Firefox
 - Version: 2.7.3

**Comment by aknarts** [comment]
Hi @iSaluki sorry for the trouble. I guess you did try opening the application again right? I remember this being an issue a while back that it did not switch the first time.

Do logs provide some insight? (be aware that debug might contain sensitive information)
```
flatpak run io.github.achetagames.epic_asset_manager
```
might output some logs.

**Comment by iSaluki** [comment]
Hi there, 

I have managed to resolve this issue. It was simply caused by an outdated sid. I hadn't realized that they expired after one use, so was entering an older one, and as there isn't an error screen for a bad sid, I assume that's why it sat on the authenticating window.

**Comment by aknarts** [comment]
@iSaluki I will keep this open as this is an indication that there needs to be more visibility towards the user in case login fails(and also it should not be stuck on the Authenticating screen).

**Comment by iSaluki** [comment]
Alright 👍
